import { Router } from "express";
import multer from "multer";
import { z } from "zod";

import { AnomalyAlertModel, CarbonForecastModel, DeviceModel, ForestAnalysisModel, ProjectModel } from "../../db/models.js";
import { ingestReading } from "../../integrations/anomaly-ml/client.js";
import { requestCarbonForecast } from "../../integrations/carbon-ml/client.js";
import { forestQueue } from "../../jobs/forest.queue.js";
import { HttpError } from "../../utils/http-error.js";
import { putObject } from "../../integrations/storage.js";
import { authenticate } from "../auth/auth.js";

const id = z.string().regex(/^[a-f\d]{24}$/i, "Invalid resource ID.");
const scenario = z.object({ projectId: id, hours: z.coerce.number().int().min(1).max(168).default(24), region: z.enum(["demo", "low_carbon_demo", "high_carbon_demo"]).default("demo"), efficiency_percent: z.coerce.number().min(0).max(40).default(0), renewable_growth_percent: z.coerce.number().min(-50).max(300).default(0), temperature_delta_c: z.coerce.number().min(-10).max(10).default(0), custom_factor_kg_per_kwh: z.coerce.number().positive().max(2).optional() });
const reading = z.object({ projectId: id, deviceId: z.string().min(1).max(64), energy_kwh: z.number().min(0).max(100_000), timestamp: z.string().datetime({ offset: true }), message_id: z.string().max(128).optional(), temperature: z.number().min(-80).max(150).optional(), voltage: z.number().min(0).max(1_000).optional(), current: z.number().min(0).max(10_000).optional() });
const forest = z.object({ projectId: id, west: z.number().min(-180).max(180), south: z.number().min(-90).max(90), east: z.number().min(-180).max(180), north: z.number().min(-90).max(90), before_start: z.string().date(), before_end: z.string().date(), after_start: z.string().date(), after_end: z.string().date(), max_cloud: z.number().min(0).max(90).default(20), sensitivity: z.number().min(0).max(1).default(0.55), minimum_patch_hectares: z.number().min(0.05).max(50).default(0.5) }).superRefine((value, context) => { if (value.west >= value.east || value.south >= value.north || value.before_start > value.before_end || value.before_end >= value.after_start || value.after_start > value.after_end) context.addIssue({ code: "custom", message: "Invalid bounds or date ordering." }); });
export const mlRouter = Router();
mlRouter.use(authenticate);
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 15_000_000, files: 2 }, fileFilter: (_request, file, callback) => callback(null, ["image/png", "image/jpeg", "image/webp", "image/tiff"].includes(file.mimetype)) });
async function ownsProject(projectId: string, userId: string): Promise<void> { if (!(await ProjectModel.exists({ _id: projectId, $or: [{ ownerId: userId }, { memberIds: userId }] }))) throw new HttpError(404, "PROJECT_NOT_FOUND", "Project not found."); }
mlRouter.post("/carbon/forecasts", async (request, response) => { const input = scenario.parse(request.body); await ownsProject(input.projectId, request.auth!.userId); const { projectId, ...mlInput } = input; const result = await requestCarbonForecast(mlInput, request.requestId); const forecast = await CarbonForecastModel.create({ projectId, requestedBy: request.auth!.userId, request: mlInput, result, model: result.model }); response.status(201).json({ data: forecast }); });
mlRouter.post("/anomaly/readings", async (request, response) => { const input = reading.parse(request.body); await ownsProject(input.projectId, request.auth!.userId); const device = await DeviceModel.findOneAndUpdate({ projectId: input.projectId, externalId: input.deviceId }, { $setOnInsert: { name: input.deviceId } }, { upsert: true, new: true }); const { deviceId, ...body } = input; const mlInput: Record<string, unknown> = { ...body }; delete mlInput.projectId; const result = await ingestReading({ ...mlInput, device_id: deviceId, user_id: request.auth!.userId }, request.requestId); const alert = await AnomalyAlertModel.findOneAndUpdate({ projectId: input.projectId, upstreamAlertId: result.alert_id }, { projectId: input.projectId, deviceId: device._id, upstreamAlertId: result.alert_id, payload: result, status: result.status, severity: result.severity }, { upsert: true, new: true }); response.status(201).json({ data: alert }); });
mlRouter.post("/forest/analyses", async (request, response) => { const input = forest.parse(request.body); await ownsProject(input.projectId, request.auth!.userId); const { projectId, ...analysisRequest } = input; const analysis = await ForestAnalysisModel.create({ projectId, requestedBy: request.auth!.userId, request: analysisRequest }); const job = await forestQueue.add("satellite-detection", { analysisId: String(analysis._id) }, { attempts: 3, backoff: { type: "exponential", delay: 5_000 }, removeOnComplete: 100, removeOnFail: 500 }); if (job.id) analysis.jobId = job.id; await analysis.save(); response.status(202).json({ data: analysis }); });
mlRouter.post("/forest/analyses/upload", upload.fields([{ name: "before", maxCount: 1 }, { name: "after", maxCount: 1 }]), async (request, response) => { const files = request.files as Record<string, Express.Multer.File[]>; const before = files?.before?.[0]; const after = files?.after?.[0]; if (!before || !after) throw new HttpError(400, "FOREST_IMAGES_REQUIRED", "Both before and after images are required."); const input = z.object({ projectId: id, west: z.coerce.number().min(-180).max(180), south: z.coerce.number().min(-90).max(90), east: z.coerce.number().min(-180).max(180), north: z.coerce.number().min(-90).max(90), sensitivity: z.coerce.number().min(0).max(1).default(0.55), minimum_patch_hectares: z.coerce.number().min(0.05).max(50).default(0.5) }).parse(request.body); await ownsProject(input.projectId, request.auth!.userId); const prefix = `forest/${input.projectId}/${crypto.randomUUID()}`; const keys = await Promise.all([putObject(`${prefix}/before`, before.buffer, before.mimetype), putObject(`${prefix}/after`, after.buffer, after.mimetype)]); const { projectId, ...analysisRequest } = input; const analysis = await ForestAnalysisModel.create({ projectId, requestedBy: request.auth!.userId, request: analysisRequest, artifactKeys: keys }); const job = await forestQueue.add("manual-detection", { analysisId: String(analysis._id), kind: "manual" }, { attempts: 3, backoff: { type: "exponential", delay: 5_000 } }); if (job.id) analysis.jobId = job.id; await analysis.save(); response.status(202).json({ data: analysis }); });
mlRouter.get("/forest/analyses/:id", async (request, response) => { const analysisId = id.parse(request.params.id); const analysis = await ForestAnalysisModel.findById(analysisId); if (!analysis || !String(analysis.projectId)) throw new HttpError(404, "ANALYSIS_NOT_FOUND", "Analysis not found."); await ownsProject(String(analysis.projectId), request.auth!.userId); response.json({ data: analysis }); });
