"use client";

import { FormEvent, useMemo, useRef, useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { motion, useReducedMotion } from "motion/react";
import { ArrowDownRight, ArrowLeft, ArrowUpRight, CloudSun, Database, Leaf, LoaderCircle, LogOut, RefreshCw, Sparkles, Timer, TriangleAlert, Zap } from "lucide-react";

import { useAuth } from "../auth/auth-provider";
import { useActiveProject, useProjects } from "../projects/project-provider";
import { useCarbonContext, useCarbonForecasts, useCreateCarbonForecast } from "../../lib/api/hooks";
import type { CarbonForecastDocument, CarbonForecastInput, CarbonForecastResult } from "../../lib/api/schemas";
import styles from "./carbon-dashboard.module.css";

const ReactECharts = dynamic(() => import("echarts-for-react"), { ssr: false });
type ForecastHours = 24 | 72 | 168;
type Region = "demo" | "low_carbon_demo" | "high_carbon_demo";

function formatNumber(value: number, digits = 1) { return new Intl.NumberFormat("en-IN", { maximumFractionDigits: digits }).format(value); }
function formatCarbon(value: number) { return value >= 1_000 ? `${formatNumber(value / 1_000, 2)} t` : `${formatNumber(value, 1)} kg`; }
function formatDate(value: string) { return new Date(value).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }); }

function buildTimelineOption(result: CarbonForecastResult, animate: boolean) {
  const labels = result.forecast.map((point) => new Date(point.timestamp).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit" }));
  return {
    animation: animate, animationDuration: 900,
    grid: { left: 7, right: 10, top: 34, bottom: 12, containLabel: true },
    tooltip: { trigger: "axis", backgroundColor: "#081410", borderColor: "rgba(79,166,224,0.28)", borderWidth: 1, textStyle: { color: "#deeae4", fontSize: 10 } }, legend: { show: false },
    xAxis: { type: "category", data: labels, boundaryGap: false, axisTick: { show: false }, axisLine: { lineStyle: { color: "rgba(143,169,154,0.14)" } }, axisLabel: { color: "#648070", fontSize: 9, interval: Math.max(0, Math.floor(labels.length / 7)) } },
    yAxis: [
      { type: "value", name: "kWh", nameTextStyle: { color: "#648070", fontSize: 9 }, axisTick: { show: false }, axisLine: { show: false }, axisLabel: { color: "#648070", fontSize: 9 }, splitLine: { lineStyle: { color: "rgba(143,169,154,0.1)", type: "dashed" } } },
      { type: "value", name: "kgCO₂e", nameTextStyle: { color: "#648070", fontSize: 9 }, axisTick: { show: false }, axisLine: { show: false }, axisLabel: { color: "#648070", fontSize: 9 }, splitLine: { show: false } },
    ],
    series: [
      { name: "Lower 90% energy estimate", type: "line", data: result.forecast.map((point) => point.lower), symbol: "none", lineStyle: { color: "rgba(143,169,154,0.56)", width: 1, type: "dashed" } },
      { name: "Upper 90% energy estimate", type: "line", data: result.forecast.map((point) => point.upper), symbol: "none", lineStyle: { color: "rgba(143,169,154,0.56)", width: 1, type: "dashed" } },
      { name: "Forecast energy", type: "line", data: result.forecast.map((point) => point.energy_kwh), symbol: "circle", symbolSize: 4, smooth: 0.28, lineStyle: { color: "#4fa6e0", width: 2.4 }, itemStyle: { color: "#4fa6e0", borderColor: "#07120b", borderWidth: 1.5 } },
      { name: "Forecast carbon", type: "line", yAxisIndex: 1, data: result.forecast.map((point) => point.co2_kg), symbol: "none", smooth: 0.28, lineStyle: { color: "#00e87a", width: 2 }, areaStyle: { color: "rgba(0,232,122,0.08)" } },
    ],
  };
}

function buildBreakdownOption(result: CarbonForecastResult, animate: boolean) {
  const renewable = Math.min(result.summary.renewable_energy_kwh, result.summary.total_energy_kwh);
  const other = Math.max(0, result.summary.total_energy_kwh - renewable);
  return { animation: animate, tooltip: { trigger: "item", formatter: "{b}: {c} kWh ({d}%)", backgroundColor: "#081410", borderColor: "rgba(0,232,122,0.24)", textStyle: { color: "#deeae4", fontSize: 10 } }, series: [{ type: "pie", radius: ["64%", "82%"], center: ["50%", "50%"], startAngle: 90, label: { show: false }, itemStyle: { borderColor: "#07110d", borderWidth: 3 }, data: [{ name: "Renewable energy", value: Number(renewable.toFixed(2)), itemStyle: { color: "#00e87a" } }, { name: "Other energy", value: Number(other.toFixed(2)), itemStyle: { color: "#4f7968" } }] }] };
}

function LoadingState() { return <div className={styles.state} role="status"><LoaderCircle className={styles.spinner} size={24} /><div><strong>Loading live carbon intelligence</strong><p>Retrieving the selected project, persisted forecasts and model context.</p></div></div>; }
function EmptyState({ onCreate, pending }: { onCreate: () => void; pending: boolean }) { return <div className={styles.state}><Database size={25} /><div><strong>No forecast exists for this project</strong><p>Run the current scenario to create and persist its first Carbon forecast.</p></div><button type="button" className={styles.retryButton} onClick={onCreate} disabled={pending}>{pending ? "Running…" : "Run forecast"}</button></div>; }
function ErrorState({ error, onRetry }: { error: unknown; onRetry: () => void }) { return <div className={styles.state} role="alert"><TriangleAlert size={25} /><div><strong>Carbon Intelligence is unavailable</strong><p>{error instanceof Error ? error.message : "The live model response could not be loaded."}</p></div><button type="button" className={styles.retryButton} onClick={onRetry}>Retry</button></div>; }

export function CarbonDashboard() {
  const rootRef = useRef<HTMLDivElement>(null); const reducedMotion = useReducedMotion(); const { logout } = useAuth(); const { projects } = useProjects(); const { activeProject, activeProjectId, setActiveProjectId } = useActiveProject();
  const [hours, setHours] = useState<ForecastHours>(72); const [region, setRegion] = useState<Region>("demo"); const [efficiency, setEfficiency] = useState(0); const [renewableGrowth, setRenewableGrowth] = useState(0); const [temperatureDelta, setTemperatureDelta] = useState(0); const [latestCreated, setLatestCreated] = useState<{ projectId: string; record: CarbonForecastDocument } | null>(null);
  const contextQuery = useCarbonContext(activeProjectId); const forecastsQuery = useCarbonForecasts(activeProjectId); const createForecast = useCreateCarbonForecast(activeProjectId);
  const record = latestCreated?.projectId === activeProjectId ? latestCreated.record : forecastsQuery.data?.[0] ?? null; const result = record?.result;
  const timelineOption = useMemo(() => result ? buildTimelineOption(result, !reducedMotion) : null, [result, reducedMotion]); const breakdownOption = useMemo(() => result ? buildBreakdownOption(result, !reducedMotion) : null, [result, reducedMotion]);
  useGSAP(() => { if (reducedMotion) return; gsap.fromTo(".carbon-reveal", { opacity: 0, y: 24 }, { opacity: 1, y: 0, duration: 0.9, stagger: 0.09, ease: "expo.out", clearProps: "transform" }); }, { scope: rootRef, dependencies: [reducedMotion] });
  const runForecast = async (event?: FormEvent) => { event?.preventDefault(); if (!activeProjectId) return; const input: CarbonForecastInput = { hours, region, efficiency_percent: efficiency, renewable_growth_percent: renewableGrowth, temperature_delta_c: temperatureDelta }; try { const created = await createForecast.mutateAsync(input); setLatestCreated({ projectId: activeProjectId, record: created }); } catch { /* The normalized mutation error is rendered below. */ } };
  const retry = () => { void Promise.all([contextQuery.refetch(), forecastsQuery.refetch()]); };
  const isLoading = contextQuery.isLoading || forecastsQuery.isLoading; const loadError = contextQuery.error ?? forecastsQuery.error; const quality = contextQuery.data?.data_quality; const factorWarning = contextQuery.data?.emissions.warning;

  return <main ref={rootRef} className={styles.dashboard}>
    <div className={styles.ambient} aria-hidden="true" /><div className="noise-overlay" aria-hidden="true" />
    <header className={`${styles.topbar} carbon-reveal`}><Link href="/" className={styles.brand} aria-label="Return to EcoYantraSpace landing page"><span className={styles.brandMark} aria-hidden="true">⬡</span><span>ECO<span>YANTRA</span>SPACE</span></Link><div className={styles.topActions}><span className={styles.demoChip}><i aria-hidden="true" /> Live model</span><Link href="/dashboard" className={styles.backLink}><ArrowLeft size={14} /> Workspace</Link><button type="button" className={styles.backLink} onClick={() => void logout()}><LogOut size={13} /> Logout</button></div></header>
    <section className={`${styles.intro} carbon-reveal`} aria-labelledby="carbon-dashboard-title"><div><div className={styles.eyebrow}><span>01</span> Carbon Intelligence / Operational view</div><h1 id="carbon-dashboard-title">MAKE THE INVISIBLE<br /><em>DECISIVE.</em></h1><p>Run the real CarbonSense scenario model, inspect its 90% energy interval and act within the cleanest forecast window.</p></div><div className={styles.introMeta}><span>ACTIVE PROJECT</span><strong>{activeProject?.name ?? "Select a project"}</strong><span className={styles.synced}><i aria-hidden="true" /> {record ? `Persisted ${formatDate(record.createdAt)}` : "Ready for first forecast"}</span></div></section>
    <form className={`${styles.controlBar} carbon-reveal`} aria-label="Carbon forecast controls" onSubmit={runForecast}><div className={styles.rangeTabs} role="tablist" aria-label="Forecast horizon">{([24, 72, 168] as ForecastHours[]).map((option) => <button key={option} type="button" role="tab" aria-selected={hours === option} className={hours === option ? styles.activeTab : undefined} onClick={() => setHours(option)}>{option}H</button>)}</div><div className={styles.filterActions}><label className={styles.liveSelect}><span>Project</span><select value={activeProjectId ?? ""} onChange={(event) => setActiveProjectId(event.target.value)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className={styles.liveSelect}><span>Region</span><select value={region} onChange={(event) => setRegion(event.target.value as Region)}><option value="demo">Demo grid</option><option value="low_carbon_demo">Low-carbon demo</option><option value="high_carbon_demo">High-carbon demo</option></select></label><button type="button" className={styles.refreshButton} onClick={retry}><RefreshCw size={14} /> Refresh</button><button type="submit" className={styles.runButton} disabled={createForecast.isPending}>{createForecast.isPending ? <LoaderCircle className={styles.spinner} size={14} /> : <Sparkles size={14} />} Run forecast</button></div></form>
    <section className={`${styles.scenarioBar} carbon-reveal`} aria-label="Scenario inputs"><label><span>Efficiency improvement</span><input type="number" min="0" max="40" step="1" value={efficiency} onChange={(event) => setEfficiency(Number(event.target.value))} /><small>%</small></label><label><span>Renewable growth</span><input type="number" min="-50" max="300" step="1" value={renewableGrowth} onChange={(event) => setRenewableGrowth(Number(event.target.value))} /><small>%</small></label><label><span>Temperature delta</span><input type="number" min="-10" max="10" step="0.5" value={temperatureDelta} onChange={(event) => setTemperatureDelta(Number(event.target.value))} /><small>°C</small></label><div><span>Data quality</span><strong>{quality ? `${quality.status} / ${formatNumber(quality.score, 0)}` : "Unavailable"}</strong></div></section>
    {createForecast.error ? <ErrorState error={createForecast.error} onRetry={() => void runForecast()} /> : null}{!createForecast.error && isLoading ? <LoadingState /> : null}{!createForecast.error && !isLoading && loadError ? <ErrorState error={loadError} onRetry={retry} /> : null}{!createForecast.error && !isLoading && !loadError && !result ? <EmptyState onCreate={() => void runForecast()} pending={createForecast.isPending} /> : null}
    {result && timelineOption && breakdownOption ? <>
      <section className={styles.kpiGrid} aria-label="Carbon forecast indicators">{[
        { label: "Forecast emissions", value: formatCarbon(result.summary.total_co2_kg), description: `${result.hours}-hour scenario total`, meta: result.emission_factor.region, icon: CloudSun, accent: "blue" },
        { label: "Forecast energy", value: `${formatNumber(result.summary.total_energy_kwh)} kWh`, description: "Modelled operating demand", meta: result.model, icon: Zap, accent: "green" },
        { label: "Renewable energy", value: `${formatNumber(result.summary.renewable_energy_kwh)} kWh`, description: "Within forecast horizon", meta: `${formatNumber(result.summary.renewable_energy_kwh / Math.max(result.summary.total_energy_kwh, 1) * 100)}% share`, icon: Leaf, accent: "ivory" },
        { label: "Average intensity", value: formatNumber(result.summary.average_carbon_intensity, 3), unit: "kgCO₂e/kWh", description: "Scenario-weighted mean", meta: result.emission_factor.is_verified ? "Verified factor" : "Illustrative factor", icon: Sparkles, accent: "green" },
      ].map((item, index) => { const Icon = item.icon; return <motion.article key={item.label} className={`${styles.kpiCard} ${styles[`accent${item.accent[0]!.toUpperCase()}${item.accent.slice(1)}`]}`} initial={reducedMotion ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: index * 0.07, ease: [0.16, 1, 0.3, 1] }}><div className={styles.kpiTop}><span>{item.label}</span><Icon size={16} /></div><strong>{item.value}<small>{item.unit}</small></strong><div className={styles.kpiBottom}><span>{item.description}</span><b>{item.meta}</b></div><div className={styles.kpiTrace} aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /></div></motion.article>; })}</section>
      <section className={styles.primaryGrid}><article className={`${styles.panel} ${styles.timelinePanel}`}><div className={styles.panelHeader}><div><span className={styles.panelLabel}>Forecast trajectory</span><h2>Energy and carbon signal</h2></div><div className={styles.legend}><span><i className={styles.legendBlue} /> Energy</span><span><i className={styles.legendGreen} /> Carbon</span><span><i className={styles.legendMuted} /> 90% interval</span></div></div><ReactECharts option={timelineOption} style={{ height: 334, width: "100%" }} opts={{ renderer: "canvas" }} /><div className={styles.chartFoot}><div><span>Forecast horizon</span><strong>{result.hours} hours</strong></div><div><span>Cleanest load window</span><strong>{formatDate(result.summary.cleanest_window.start)}</strong></div><div><span>Shift saving</span><strong className={styles.positive}>{formatNumber(result.summary.shift_opportunity.estimated_savings_kg, 2)} kgCO₂e</strong></div></div></article><article className={`${styles.panel} ${styles.forecastPanel}`}><div className={styles.panelHeader}><div><span className={styles.panelLabel}>Current scenario</span><h2>{result.hours}H outlook</h2></div><span className={styles.liveTag}><i aria-hidden="true" /> Model complete</span></div><div className={styles.orbit} aria-hidden="true"><span /><span /><span /><b>{result.hours}<span>h</span></b></div><div className={styles.forecastMetric}><span>Expected operating emissions</span><strong>{formatCarbon(result.summary.total_co2_kg)}</strong><p><ArrowDownRight size={14} /> {result.summary.shift_opportunity.estimated_savings_kg > 0 ? `${formatNumber(result.summary.shift_opportunity.estimated_savings_kg, 2)} kg can shift` : "No shift saving identified"}</p></div><div className={styles.forecastBars}>{result.forecast.slice(0, 24).map((point) => <i key={point.timestamp} style={{ height: `${Math.max(12, point.renewable_share_percent)}%` }} />)}</div></article></section>
      <section className={styles.lowerGrid}><article className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.panelLabel}>Energy composition</span><h2>Renewable contribution</h2></div><span className={styles.tinyTotal}>{formatNumber(result.summary.total_energy_kwh)} kWh</span></div><div className={styles.breakdownBody}><div className={styles.pieWrap}><ReactECharts option={breakdownOption} style={{ height: 230, width: "100%" }} opts={{ renderer: "canvas" }} /><div><strong>{formatNumber(result.summary.renewable_energy_kwh / Math.max(result.summary.total_energy_kwh, 1) * 100)}%</strong><span>renewable</span></div></div><ul className={styles.breakdownLegend}><li><i style={{ background: "#00e87a" }} /><span>Renewable energy</span><strong>{formatNumber(result.summary.renewable_energy_kwh)} kWh</strong></li><li><i style={{ background: "#4f7968" }} /><span>Other energy</span><strong>{formatNumber(Math.max(0, result.summary.total_energy_kwh - result.summary.renewable_energy_kwh))} kWh</strong></li><li><i style={{ background: "#4fa6e0" }} /><span>Emission factor</span><strong>{formatNumber(result.emission_factor.factor_kg_per_kwh, 3)}</strong></li></ul></div></article><article className={styles.panel}><div className={styles.panelHeader}><div><span className={styles.panelLabel}>Operational detail</span><h2>Model-supported actions</h2></div><span className={styles.tinyTotal}>{result.model}</span></div><div className={styles.sourceList}><div className={styles.sourceRow}><div className={styles.sourceIcon}><Zap size={15} /></div><div><strong>Peak demand</strong><span>{formatDate(result.summary.peak_hour.timestamp)}</span></div><div><strong>{formatNumber(result.summary.peak_hour.energy_kwh)} kWh</strong><span>Forecast point</span></div></div><div className={styles.sourceRow}><div className={styles.sourceIcon}><Timer size={15} /></div><div><strong>Cleanest window</strong><span>{formatDate(result.summary.cleanest_window.start)}</span></div><div><strong>{formatNumber(result.summary.cleanest_window.average_carbon_intensity, 3)}</strong><span>kgCO₂e/kWh</span></div></div><div className={styles.sourceRow}><div className={styles.sourceIcon}><Leaf size={15} /></div><div><strong>Flexible load shift</strong><span>{formatDate(result.summary.shift_opportunity.to_timestamp)}</span></div><div><strong>{formatNumber(result.summary.shift_opportunity.flexible_load_kwh)} kWh</strong><span className={styles.positive}>{formatNumber(result.summary.shift_opportunity.estimated_savings_kg, 2)} kg saved</span></div></div></div></article></section>
      <section className={styles.insights} aria-labelledby="carbon-insights-title"><div className={styles.insightHeading}><div><span className={styles.panelLabel}>Carbon intelligence</span><h2 id="carbon-insights-title">What your data is<br /><em>asking you to do.</em></h2></div><p>{result.summary.recommendation}</p></div><div className={styles.insightGrid}>{result.summary.recommendations.slice(0, 3).map((recommendation, index) => { const Icon = [Leaf, Timer, Sparkles][index] ?? Sparkles; return <motion.article key={recommendation} className={`${styles.insightCard} ${index === 1 ? styles.insightBlue : index === 2 ? styles.insightIvory : styles.insightGreen}`} {...(reducedMotion ? {} : { whileHover: { y: -6 } })} transition={{ duration: 0.3 }}><span className={styles.insightIcon}><Icon size={17} /></span><div><span className={styles.insightLabel}>0{index + 1} / Model recommendation</span><h3>{recommendation}</h3><p>Generated by {result.model} from the selected project scenario.</p></div><ArrowUpRight className={styles.insightArrow} size={16} /></motion.article>; })}</div></section>
    </> : null}
    <footer className={styles.footer}><span>EcoYantraSpace / Carbon Intelligence</span><span>{factorWarning ?? "Live Node API · MongoDB persistence · Carbon ML"}</span></footer>
  </main>;
}
