"use client";

import { FormEvent, useMemo, useRef, useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { motion, useReducedMotion } from "motion/react";
import { Activity, ArrowLeft, ArrowUpRight, Braces, Check, ChevronDown, Clock3, Cpu, Database, Gauge, LoaderCircle, LogOut, Radio, RefreshCw, ShieldAlert, Sparkles, TriangleAlert, Zap } from "lucide-react";

import { useAuth } from "../auth/auth-provider";
import { useActiveProject, useProjects } from "../projects/project-provider";
import { useAnomalyDashboard, useAnomalyDevices, useSubmitAnomalyReading } from "../../lib/api/hooks";
import type { AnomalyAlertPayload, AnomalyReadingInput } from "../../lib/api/schemas";
import styles from "./anomaly-dashboard.module.css";

const ReactECharts = dynamic(() => import("echarts-for-react"), { ssr: false });
type PeriodHours = 24 | 168 | 720;
type ReadingForm = { device_id: string; energy_kwh: string; timestamp: string; message_id: string; temperature: string; voltage: string; current: string };

function optionalNumber(value: string) { return value.trim() === "" ? undefined : Number(value); }
function timelineOption(points: Array<{ timestamp: string; energy_kwh: number; lower_bound: number; upper_bound: number; status: "NORMAL" | "ANOMALY"; score: number }>, animate: boolean) {
  const labels = points.map((point) => new Date(point.timestamp).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit" }));
  return { animation: animate, animationDuration: 850, grid: { left: 8, right: 14, top: 30, bottom: 12, containLabel: true }, tooltip: { trigger: "axis", backgroundColor: "#0b140f", borderColor: "rgba(232,170,58,0.28)", borderWidth: 1, textStyle: { color: "#deeae4", fontSize: 11 } }, xAxis: { type: "category", data: labels, boundaryGap: false, axisTick: { show: false }, axisLine: { lineStyle: { color: "rgba(143,169,154,0.14)" } }, axisLabel: { color: "#648070", fontSize: 9, interval: Math.max(Math.floor(points.length / 7), 1) } }, yAxis: { type: "value", name: "kWh", nameTextStyle: { color: "#648070", fontSize: 9 }, axisTick: { show: false }, axisLine: { show: false }, axisLabel: { color: "#648070", fontSize: 9 }, splitLine: { lineStyle: { color: "rgba(143,169,154,0.10)", type: "dashed" } } }, series: [{ name: "Expected maximum", type: "line", data: points.map((point) => point.upper_bound), symbol: "none", lineStyle: { color: "#e8aa3a", width: 1.2, type: "dashed" } }, { name: "Expected minimum", type: "line", data: points.map((point) => point.lower_bound), symbol: "none", lineStyle: { color: "#e8aa3a", width: 1.2, type: "dashed" } }, { name: "Observed energy", type: "line", data: points.map((point) => point.energy_kwh), symbol: "circle", symbolSize: 4, smooth: 0.25, lineStyle: { color: "#7ccfb1", width: 2.2 }, itemStyle: { color: "#7ccfb1", borderColor: "#07120b", borderWidth: 1.5 } }, { name: "Anomaly", type: "scatter", data: points.map((point, index) => point.status === "ANOMALY" ? [index, point.energy_kwh, point.score] : null).filter(Boolean), symbolSize: 11, itemStyle: { color: "#ff665e", shadowBlur: 12, shadowColor: "rgba(255,102,94,0.6)" } }] };
}
function signalOption(signals: AnomalyAlertPayload["signals"], animate: boolean) { return { animation: animate, animationDuration: 700, grid: { left: 4, right: 12, top: 8, bottom: 4, containLabel: true }, xAxis: { type: "value", min: 0, max: 1, show: false }, yAxis: { type: "category", inverse: true, data: signals.map((signal) => signal.name), axisTick: { show: false }, axisLine: { show: false }, axisLabel: { color: "#8aa99a", fontSize: 10, width: 105, overflow: "truncate" } }, series: [{ type: "bar", data: signals.map((signal) => signal.contribution), barWidth: 8, showBackground: true, backgroundStyle: { color: "rgba(143,169,154,0.08)", borderRadius: 5 }, itemStyle: { color: "#e8aa3a", borderRadius: 5 }, label: { show: true, position: "right", color: "#deeae4", fontSize: 9, formatter: "{c}" } }] }; }
function DataState({ title, body, error, onRetry }: { title: string; body: string; error?: boolean; onRetry?: () => void }) { return <div className={styles.dataState} role={error ? "alert" : "status"}>{error ? <TriangleAlert size={20} /> : <Database size={20} />}<div><strong>{title}</strong><span>{body}</span></div>{onRetry ? <button type="button" onClick={onRetry}><RefreshCw size={12} /> Retry</button> : null}</div>; }

export function AnomalyDashboard() {
  const rootRef = useRef<HTMLDivElement>(null); const reducedMotion = useReducedMotion(); const { logout } = useAuth(); const { projects } = useProjects(); const { activeProject, activeProjectId, setActiveProjectId } = useActiveProject();
  const [periodHours, setPeriodHours] = useState<PeriodHours>(168); const [selection, setSelection] = useState<{ projectId: string; deviceId: string } | null>(null); const [latestResult, setLatestResult] = useState<{ projectId: string; result: AnomalyAlertPayload } | null>(null); const [inputError, setInputError] = useState<string | null>(null);
  const [form, setForm] = useState<ReadingForm>({ device_id: "", energy_kwh: "", timestamp: "", message_id: "", temperature: "", voltage: "", current: "" });
  const devicesQuery = useAnomalyDevices(activeProjectId); const devices = devicesQuery.data ?? []; const deviceId = selection?.projectId === activeProjectId ? selection.deviceId : devices[0]?.device_id ?? ""; const dashboardQuery = useAnomalyDashboard(activeProjectId, deviceId, periodHours); const submitReading = useSubmitAnomalyReading(activeProjectId); const dashboard = dashboardQuery.data;
  const currentResult = latestResult?.projectId === activeProjectId ? latestResult.result : dashboard?.alerts[0] ?? null; const chartOption = useMemo(() => timelineOption(dashboard?.timeline ?? [], !reducedMotion), [dashboard?.timeline, reducedMotion]);
  useGSAP(() => { if (reducedMotion) return; gsap.fromTo(".anomaly-reveal", { opacity: 0, y: 22 }, { opacity: 1, y: 0, duration: 0.88, stagger: 0.075, ease: "expo.out", clearProps: "transform" }); }, { scope: rootRef, dependencies: [reducedMotion] });
  const selectDevice = (nextId: string) => { const next = devices.find((device) => device.device_id === nextId); if (activeProjectId) setSelection({ projectId: activeProjectId, deviceId: nextId }); setLatestResult(null); setForm((current) => ({ ...current, device_id: nextId, energy_kwh: next?.latest_energy_kwh?.toString() ?? current.energy_kwh, message_id: `web-${crypto.randomUUID()}`, timestamp: new Date().toISOString() })); };
  const updateForm = (key: keyof ReadingForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const evaluate = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!activeProjectId) return; const suppliedTimestamp = form.timestamp.trim(); const timestampDate = suppliedTimestamp ? new Date(suppliedTimestamp) : null; if (timestampDate && Number.isNaN(timestampDate.getTime())) { setInputError("Timestamp must be a valid timezone-aware ISO-8601 value, such as 2026-08-15T10:00:00Z."); return; } setInputError(null); const input: AnomalyReadingInput = { device_id: form.device_id.trim(), energy_kwh: Number(form.energy_kwh), ...(timestampDate ? { timestamp: timestampDate.toISOString() } : {}), ...(form.message_id.trim() ? { message_id: form.message_id.trim() } : {}), ...(optionalNumber(form.temperature) === undefined ? {} : { temperature: optionalNumber(form.temperature) }), ...(optionalNumber(form.voltage) === undefined ? {} : { voltage: optionalNumber(form.voltage) }), ...(optionalNumber(form.current) === undefined ? {} : { current: optionalNumber(form.current) }) }; try { const created = await submitReading.mutateAsync(input); setLatestResult({ projectId: activeProjectId, result: created.result }); setSelection({ projectId: activeProjectId, deviceId: created.device.device_id }); setForm((current) => ({ ...current, device_id: created.device.device_id, message_id: `web-${crypto.randomUUID()}`, timestamp: new Date().toISOString() })); } catch { /* The mutation exposes the normalized API error below. */ } };

  return <main ref={rootRef} className={styles.dashboard}>
    <div className={styles.ambient} aria-hidden="true" /><div className="noise-overlay" aria-hidden="true" />
    <header className={`${styles.topbar} anomaly-reveal`}><Link href="/" className={styles.brand}><span className={styles.brandMark}>⬡</span><span>ECO<span>YANTRA</span>SPACE</span></Link><div className={styles.topActions}><span className={styles.contractChip}><i /> Live project data</span><Link href="/dashboard" className={styles.backLink}><ArrowLeft size={14} /> Workspace</Link><button type="button" className={styles.backLink} onClick={() => void logout()}><LogOut size={13} /> Logout</button></div></header>
    <section className={`${styles.intro} anomaly-reveal`} aria-labelledby="anomaly-dashboard-title"><div><div className={styles.eyebrow}><span>02</span> Anomaly Intelligence / Explainable detection</div><h1 id="anomaly-dashboard-title">FIND THE SIGNAL.<br /><em>EXPLAIN THE BREAK.</em></h1></div><p>Submit real project telemetry through the Node API, then inspect the model’s exact score, evidence and recommended action.</p></section>
    <section className={`${styles.controls} anomaly-reveal`} aria-label="Dashboard filters"><label><span>Project</span><div><Database size={14} /><select value={activeProjectId ?? ""} onChange={(event) => setActiveProjectId(event.target.value)}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><ChevronDown size={13} /></div></label><label><span>Persisted device</span><div><Cpu size={14} />{devices.length ? <select value={deviceId} onChange={(event) => selectDevice(event.target.value)}>{devices.map((device) => <option key={device.id} value={device.device_id}>{device.name} · #{device.device_id}</option>)}</select> : <input className={styles.newDeviceInput} value={form.device_id} maxLength={64} onChange={(event) => updateForm("device_id", event.target.value)} aria-label="New device ID" />}<ChevronDown size={13} /></div></label><div className={styles.deviceMeta}><span>Active project</span><strong>{activeProject?.name ?? "None"}</strong></div><div className={styles.periodTabs}>{([24, 168, 720] as PeriodHours[]).map((hours) => <button key={hours} type="button" className={periodHours === hours ? styles.periodActive : undefined} onClick={() => setPeriodHours(hours)}>{hours === 24 ? "24H" : hours === 168 ? "7D" : "30D"}</button>)}</div></section>

    {dashboard ? <section className={styles.kpiGrid} aria-label="Supported anomaly metrics">{[
      { label: "Latest observed", value: dashboard.device.latest_energy_kwh === null ? "—" : dashboard.device.latest_energy_kwh.toFixed(1), unit: dashboard.device.latest_energy_kwh === null ? undefined : "kWh", detail: dashboard.device.name, icon: Zap, tone: "mint" },
      { label: "Expected envelope", value: dashboard.device.expected_range ? `${dashboard.device.expected_range.min}–${dashboard.device.expected_range.max}` : "—", unit: dashboard.device.expected_range ? "kWh" : undefined, detail: dashboard.device.expected_range ? "Returned model baseline" : "No result yet", icon: Gauge, tone: "amber" },
      { label: "Anomaly rate", value: `${(dashboard.anomaly_rate * 100).toFixed(1)}%`, detail: `${dashboard.alerts.length} persisted alerts`, icon: Activity, tone: "red" },
      { label: "Latest score", value: dashboard.device.latest_score === null ? "—" : dashboard.device.latest_score.toFixed(2), detail: dashboard.device.latest_status ?? "No result yet", icon: ShieldAlert, tone: dashboard.device.latest_status === "ANOMALY" ? "red" : "green" },
      { label: "Readings seen", value: dashboard.device.readings_seen.toString(), detail: `${dashboard.period_hours} hour project window`, icon: Database, tone: "ivory" },
    ].map((item, index) => { const Icon = item.icon; return <motion.article key={item.label} className={`${styles.kpi} ${styles[`kpi${item.tone[0]!.toUpperCase()}${item.tone.slice(1)}`]}`} initial={reducedMotion ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .48, delay: index * .06 }}><div><span>{item.label}</span><Icon size={15} /></div><strong>{item.value}<small>{item.unit}</small></strong><p>{item.detail}</p></motion.article>; })}</section> : null}

    {devicesQuery.isLoading || (deviceId && dashboardQuery.isLoading) ? <DataState title="Loading project telemetry" body="Reading persisted devices and model results from the Node API." /> : null}
    {devicesQuery.error ? <DataState error title="Device history unavailable" body={devicesQuery.error.message} onRetry={() => void devicesQuery.refetch()} /> : null}
    {dashboardQuery.error && deviceId ? <DataState error title="Timeline unavailable" body={dashboardQuery.error.message} onRetry={() => void dashboardQuery.refetch()} /> : null}
    {!devicesQuery.isLoading && !devicesQuery.error && !devices.length ? <DataState title="No device readings yet" body="Submit the first real reading below. The project timeline will appear after persistence." /> : null}
    {dashboard ? <section className={`${styles.timelinePanel} anomaly-reveal`}><div className={styles.panelHeader}><div><span>Project-scoped timeline</span><h2>Observed energy against expected range</h2></div><div className={styles.timelineLegend}><span><i className={styles.observedDot} /> Observed</span><span><i className={styles.expectedDot} /> Expected bounds</span><span><i className={styles.anomalyDot} /> Anomaly</span></div></div>{dashboard.timeline.length ? <ReactECharts option={chartOption} style={{ height: 365, width: "100%" }} opts={{ renderer: "canvas" }} /> : <DataState title="No readings in this period" body="Change the period or submit another reading." />}<div className={styles.timelineFooter}><span><Clock3 size={13} /> Period: {periodHours} hours</span><span><Radio size={13} /> Persisted inputs and actual model outputs</span><strong>Device #{dashboard.device.device_id}</strong></div></section> : null}

    <section className={styles.workbench}>
      <form className={`${styles.inputPanel} anomaly-reveal`} onSubmit={evaluate}><div className={styles.panelHeader}><div><span>Model input</span><h2>Submit one energy reading</h2></div><span className={styles.schemaTag}><Braces size={12} /> ReadingIn</span></div><div className={styles.requiredGrid}><label><span>device_id <b>required</b></span><input required maxLength={64} value={form.device_id} onChange={(event) => updateForm("device_id", event.target.value)} /></label><label><span>energy_kwh <b>required</b></span><input type="number" min="0" max="100000" step="0.1" required value={form.energy_kwh} onChange={(event) => updateForm("energy_kwh", event.target.value)} /></label><label className={styles.fullField}><span>timestamp <b>optional / timezone-aware</b></span><input type="text" placeholder="2026-08-15T10:00:00.000Z" value={form.timestamp} onChange={(event) => updateForm("timestamp", event.target.value)} /></label><label className={styles.fullField}><span>message_id <small>optional</small></span><input maxLength={128} value={form.message_id} onChange={(event) => updateForm("message_id", event.target.value)} /></label></div><details className={styles.optionalFields}><summary>Accepted optional metadata <ChevronDown size={13} /></summary><p>Temperature, voltage and current are accepted and persisted, but the current detector does not use them as model features.</p><div className={styles.optionalGrid}><label><span>temperature</span><input type="number" min="-80" max="150" step="0.1" value={form.temperature} onChange={(event) => updateForm("temperature", event.target.value)} /></label><label><span>voltage</span><input type="number" min="0" max="1000" step="0.1" value={form.voltage} onChange={(event) => updateForm("voltage", event.target.value)} /></label><label><span>current</span><input type="number" min="0" max="10000" step="0.1" value={form.current} onChange={(event) => updateForm("current", event.target.value)} /></label></div></details>{inputError ? <p className={styles.formError}>{inputError}</p> : null}{submitReading.error ? <p className={styles.formError}>{submitReading.error.message}</p> : null}<div className={styles.formActions}><button type="button" className={styles.resetButton} onClick={() => { setInputError(null); updateForm("timestamp", new Date().toISOString()); }}><RefreshCw size={13} /> Use current time</button><button type="submit" className={styles.evaluateButton} disabled={submitReading.isPending}>{submitReading.isPending ? <LoaderCircle className={styles.spinner} size={15} /> : <Sparkles size={15} />} {submitReading.isPending ? "Evaluating…" : "Evaluate real reading"} <ArrowUpRight size={14} /></button></div></form>
      {currentResult ? <article className={`${styles.resultPanel} ${currentResult.status === "ANOMALY" ? styles.resultAnomaly : styles.resultNormal} anomaly-reveal`} aria-live="polite"><div className={styles.resultTop}><div><span>Model output</span><h2>Explainable result</h2></div><span className={styles.schemaTag}><Braces size={12} /> AlertOut</span></div><div className={styles.statusRow}><div className={styles.scoreOrb}><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="43" /><circle cx="50" cy="50" r="43" pathLength="100" strokeDasharray={`${currentResult.score * 100} 100`} /></svg><strong>{currentResult.score.toFixed(2)}</strong><span>score</span></div><div><span className={styles.statusLabel}><i /> {currentResult.status}</span><h3>{currentResult.severity} severity</h3><p>Observed <strong>{currentResult.observed.toFixed(1)} kWh</strong> against <strong>{currentResult.expected_range.min}–{currentResult.expected_range.max} kWh</strong>.</p></div></div><div className={styles.reasonBlock}><span>Reasons</span>{currentResult.reasons.map((reason) => <p key={reason}><Check size={12} /> {reason}</p>)}</div>{currentResult.signals.length ? <div className={styles.signalBlock}><div><span>Signal contributions</span><small>Returned evidence only</small></div><ReactECharts option={signalOption(currentResult.signals, !reducedMotion)} style={{ height: 155, width: "100%" }} opts={{ renderer: "canvas" }} /><ul className={styles.signalEvidence}>{currentResult.signals.map((signal) => <li key={signal.name}><div><strong>{signal.name}</strong><span>value {signal.value.toFixed(2)} · contribution {signal.contribution.toFixed(2)}</span></div><p>{signal.interpretation}</p></li>)}</ul></div> : <div className={styles.noSignals}><Check size={15} /><span>No contributing anomaly signals were returned.</span></div>}<div className={styles.actionBlock}><ShieldAlert size={17} /><div><span>Recommended action</span><p>{currentResult.recommended_action}</p></div></div><div className={styles.resultMeta}><span>alert_id / {currentResult.alert_id}</span><span>{new Date(currentResult.timestamp).toLocaleString("en-IN")}</span></div></article> : <DataState title="Awaiting a model result" body="Submit a reading to populate the exact AlertOut response." />}
    </section>
    {dashboard?.alerts.length ? <section className={`${styles.alertsSection} anomaly-reveal`}><div className={styles.alertHeading}><div><span>Persisted project alerts</span><h2>Recent investigations</h2></div><p>Every record is an actual model response retained through the authorized Node API.</p></div><div className={styles.alertGrid}>{dashboard.alerts.map((alert, index) => <motion.article key={alert.alert_id} className={styles.alertCard} {...(reducedMotion ? {} : { whileHover: { y: -4 } })}><div><span className={`${styles.severity} ${styles[`severity${alert.severity}`]}`}>{alert.severity}</span><span>{new Date(alert.timestamp).toLocaleString("en-IN")}</span></div><strong>{alert.observed.toFixed(1)} kWh observed</strong><p>{alert.reasons[0]}</p><footer><span>Score {alert.score.toFixed(2)}</span><span>#{index + 1}</span></footer></motion.article>)}</div></section> : null}
    <footer className={styles.footer}><span>EcoYantraSpace / Anomaly Intelligence</span><span>Node API · MongoDB project history · Anomaly ML</span></footer>
  </main>;
}
